import { FitCourse } from '@/sharedTypes/sharedTypes';

export const fitCourses: FitCourse[] = [
  {
    id: 1,
    title: 'Йога',
    days: 25,
    duration: { min: 20, max: 50 },
    // difficulty: DifficultyLevel.Medium,
    image: '/img/skill1.svg',
    logo: null,
    starredUsers: [],
  },
  {
    id: 2,
    title: 'Стретчинг',
    days: 25,
    duration: { min: 20, max: 50 },
    // difficulty: DifficultyLevel.Medium,
    image: '/img/skill2.svg',
    logo: null,
    starredUsers: [],
  },
  {
    id: 3,
    title: 'Фитнес',
    days: 25,
    duration: { min: 20, max: 50 },
    // difficulty: DifficultyLevel.Medium,
    image: '/img/skill3.svg',
    logo: null,
    starredUsers: [],
  },
  {
    id: 4,
    title: 'Степ-аэробика',
    days: 25,
    duration: { min: 20, max: 50 },
    // difficulty: DifficultyLevel.Medium,
    image: '/img/skill4.svg',
    logo: null,
    starredUsers: [],
  },
  {
    id: 5,
    title: 'Бодифлекс',
    days: 25,
    duration: { min: 20, max: 50 },
    // difficulty: DifficultyLevel.Medium,
    image: '/img/skill5.svg',
    logo: null,
    starredUsers: [],
  },
];


// import { FitCourseType } from '@/sharedTypes/sharedTypes';

// export const data: FitCourseType[] = [
//   {
//     _id: 1,
//     name: 'Йога',
//     image: '/img/skill1.svg',
//     number_of_days: 25,
//     duration: { from: 20, to: 50 },
//     difficulty: 3,
//     logo: null,
//     stared_user: [],
//   },
//   {
//     _id: 2,
//     name: 'Стретчинг',
//     number_of_days: 25,
//     duration: { from: 20, to: 50 },
//     difficulty: 3,
//     image: '/img/skill2.svg',
//     logo: null,
//     stared_user: [],
//   },
//   {
//     _id: 3,
//     name: 'Фитнес',
//     number_of_days: 25,
//     duration: { from: 20, to: 50 },
//     difficulty: 3,
//     image: '/img/skill3.svg',
//     logo: null,
//     stared_user: [],
//   },
//   {
//     _id: 4,
//     name: 'Степ-аэробика',
//     number_of_days: 25,
//     duration: { from: 20, to: 50 },
//     difficulty: 3,
//     image: '/img/skill4.svg',
//     logo: null,
//     stared_user: [],
//   },
//   {
//     _id: 5,
//     name: 'Бодифлекс',
//     number_of_days: 25,
//     duration: { from: 20, to: 50 },
//     difficulty: 3,
//     image: '/img/skill5.svg',
//     logo: null,
//     stared_user: [],
//   },
// ];
