import { FitCourseType } from '@/sharedTypes/sharedTypes';

export const data: FitCourseType[] = [
  {
    _id: 1,
    name: 'Йога',
    image: '/img/skill1.svg',
    number_of_days: 25,
    duration: { from: 20, to: 50 },
    difficulty: 3,
    logo: null,
    stared_user: [],
  },
  {
    _id: 2,
    name: 'Стретчинг',
    number_of_days: 25,
    duration: { from: 20, to: 50 },
    difficulty: 3,
    image: '/img/skill2.svg',
    logo: null,
    stared_user: [],
  },
  {
    _id: 3,
    name: 'Фитнес',
    number_of_days: 25,
    duration: { from: 20, to: 50 },
    difficulty: 3,
    image: '/img/skill3.svg',
    logo: null,
    stared_user: [],
  },
  {
    _id: 4,
    name: 'Степ-аэробика',
    number_of_days: 25,
    duration: { from: 20, to: 50 },
    difficulty: 3,
    image: '/img/skill4.svg',
    logo: null,
    stared_user: [],
  },
  {
    _id: 5,
    name: 'Бодифлекс',
    number_of_days: 25,
    duration: { from: 20, to: 50 },
    difficulty: 3,
    image: '/img/skill5.svg',
    logo: null,
    stared_user: [],
  },
];
